FROM node:20.17.0-alpine

WORKDIR /products_service

COPY . .

RUN npm install --production

ARG PRODUCTS_SERVICE_PORT
ARG PRODUCTS_DB_SERVICE_NAME

# temporary solution; TODO: create secrets file
ARG SECRET_KEY

ENV PRODUCTS_SERVICE_PORT=${PRODUCTS_SERVICE_PORT} PRODUCTS_DB_SERVICE_NAME=${PRODUCTS_DB_SERVICE_NAME} SECRET_KEY=${SECRET_KEY}

EXPOSE ${PRODUCTS_SERVICE_PORT}

CMD [ "npm", "start" ]