FROM node:20.17.0-alpine

WORKDIR /products_service

COPY . .

RUN npm install --production

ARG PRODUCTS_SERVICE_PORT
ARG PRODUCTS_DB_SERVICE_NAME

ENV PRODUCTS_SERVICE_PORT=${PRODUCTS_SERVICE_PORT} PRODUCTS_DB_SERVICE_NAME=${PRODUCTS_DB_SERVICE_NAME}

EXPOSE ${PRODUCTS_SERVICE_PORT}

CMD [ "npm", "start" ]